### PR TITLE
17 bug for bmi with negative or zero parameter and Tests

### LINKED ISSUE #17: Bug for BMI with Negative or Zero parameter
when sending wrong business data: value 0 or negative, I get a return with a bmi equal to null or with a negative bmi.
on the server side server sees no problem,  log.warn("corresponding message") from @Slf4j is missing

image

image

### PR DESCRIPTION
**Pull request by Julia0321**

### CODE REVIEW

File: src/main/java/com/gymrats/service/CalculatorService.java [hunk 1]
```diff
@@ -28,7 +28,10 @@ public BmrNotLoggedResponse calculateBmr(BmrNotLoggedRequest requestBmr){
         float height = requestBmr.height();
         float bmr = 0;
 
-        if(sex.equals(GenderEnum.WOMAN)){
+        if(weight == 0 || weight < 0 || height == 0 || height < 0  || userAge == 0 || userAge < 0){
```
Comment (McBlankenburg) [inline src/main/java/com/gymrats/service/CalculatorService.java]: it can be written shorter <=

**Review by McBlankenburg — CHANGES_REQUESTED** [review]

File: src/main/java/com/gymrats/service/CalculatorService.java [hunk 2]
```diff
@@ -28,7 +28,10 @@ public BmrNotLoggedResponse calculateBmr(BmrNotLoggedRequest requestBmr){
...
+            throw new IllegalArgumentException();
```
Comment (McBlankenburg) [inline src/main/java/com/gymrats/service/CalculatorService.java]: no more detailed information
https://www.geeksforgeeks.org/spring-mvc-regular-expression-validation/ maybe like that?

**Review by McBlankenburg — CHANGES_REQUESTED** [review]

**Review by McBlankenburg — APPROVED** [review]
